## Level 1 — Python Fundamentals (10 Tasks)
#### Each task should be solvable using basic Python and simple logic. No ML yet.

### 1. Sum of a List

#### Write a Python function that takes a list of numbers and returns their sum without using `sum()`.

In [6]:
def sum_of_elements(lst):
    sum_ = 0
    for num in lst:
        sum_ += num
    return sum_
print(sum_of_elements([i for i in range(1, 11)]))

55


### 2. Count Occurrences

#### Write a function that counts how many times each element appears in a list. Output should be a dictionary.

In [54]:
def element_counter(lst):
    dict_ = {}
    
    for element in lst:
        if element not in dict_:
            dict_[element] = 1
        else:
            dict_[element] += 1
    return dict_

element_counter([1,1,1,2,2,3,4,4])      

{1: 3, 2: 2, 3: 1, 4: 2}

### 3. String Reverse

#### Reverse a string using slicing and also by writing a manual loop method.

In [46]:
def string_reverse(string):
    reversed_string = ''
    lst = list(i for i in range(len(string)))
    for i in reversed(lst):
        reversed_string += string[i]
    return reversed_string, string[::-1]
    
string_reverse("my name is loghman")

('namhgol si eman ym', 'namhgol si eman ym')

### 4. Check Palindrome

#### Write a function `is_palindrome(s)` that returns True if a string is a palindrome.

In [25]:
def is_palindrome(string):
    return string == string[::-1]
    
print(is_palindrome('loghman'))
print(is_palindrome('loqqol'))

False
True


### 5. Remove Duplicates

#### Given a list, return a new list with duplicates removed, preserving order.

In [29]:
def remove_dupplicates(lst):
    unique_list = []
    for element in lst:
        if element not in unique_list:
            unique_list.append(element)
    return unique_list
    
remove_dupplicates([1,1,1,2,3,3,2,5])

[1, 2, 3, 5]

### 6. Find Max and Min (without using max or min)

#### Write a function that finds the maximum and minimum of a list manually.

In [48]:
def max_min(lst):
    
    try:
        max_ = lst[0]
        min_ = lst[0]
        
        for element in lst:
            if element > max_:
                    max_ = element
            if element < min_:
                    min_ = element
            
        return max_, min_
    except:
        if len(lst) == 0:
            return "list is empty!"

print(max_min([1,2,11,1,1,5,-19])) 
max_min([])

(11, -19)


'list is empty!'

### 7. FizzBuzz

#### Classic: Print numbers 1 to 50 but

#### If divisible by 3 → print "Fizz"

#### If divisible by 5 → print "Buzz"

#### If divisible by both → print "FizzBuzz"

In [36]:
def fizz_buzz():
    for i in range(1, 51):
        if i % 3 == 0 and i % 5 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)
fizz_buzz()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


### 8. Simple Dictionary Merge

#### Merge two dictionaries; if a key appears in both, the value from the second dictionary overwrites the first.

In [49]:
def merge_dicts(dict1, dict2):

    new_dict = dict1
    
    for key, val in dict2.items():
        if key in new_dict:
            new_dict[key] = val
        else:
            new_dict[key] = val
    return new_dict

merge_dicts({1: "a", 2: "b"}, {1: "g", 3:"f"})

{1: 'g', 2: 'b', 3: 'f'}

### 9. NumPy: Create and Manipulate Arrays

#### Do the following with NumPy:

#### create a 1D array `[1,2,3,4,5]`

#### compute element-wise square

#### compute the mean

#### reshape into a 5×1 matrix

In [51]:
import numpy as np

#one_d_array = np.array([i for i in range(1, 6)])
one_d_array = np.arange(1, 6)
element_wise_square = one_d_array**2
mean = one_d_array.mean()
reshaped_array = one_d_array.reshape((5, 1))

print(one_d_array, one_d_array.shape)
print(element_wise_square)
print(mean)
print(reshaped_array, reshaped_array.shape) 

[1 2 3 4 5] (5,)
[ 1  4  9 16 25]
3.0
[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


### 10. Loop Through a File

#### Assume a file data.txt contains one number per line.

#### Write Python code to:

#### open the file

#### read all numbers

#### compute their average

##### (If no file exists, write code as if it does.)

In [53]:
def read_txt(file_path):
    count, sum_ = 0, 0
    with open(file_path) as file:
        for line in file:
            sum_ += float(line)
            count += 1
    return f" Sum of the Elements: {sum_}", f"Mean of the Elements: {sum_/count}"
        
read_txt("/home/loqman/Downloads/projs/deep-learning/technical_interview/text_file.txt")   

(' Sum of the Elements: 33.0', 'Mean of the Elements: 5.5')