## ✅ Level 2 — Intermediate Python (10 Tasks)

### 1. List Comprehension Transform

Given a list of integers, write a single list comprehension that:

squares each number

removes negative results

keeps only even squares

Example:
Input: `[1, -2, 3, -4]` → Output: `[4, 16]`

In [4]:
def transform(lst):
    if len(lst) == 0:
        return "The initial list is empty!"
    else:
        return [i**2 for i in lst if i**2 % 2 == 0]
                
print(transform([1, -2, 3, -4]), transform([]), transform([5, 4, 2, 198]))

[4, 16] The initial list is empty! [16, 4, 39204]


### 2. Flatten a Nested List

Write a function to flatten a `list` of lists (only 1 level deep).

Example:
`[[1,2],[3,4],[5]]` → `[1,2,3,4,5]`

In [13]:
def flatten_(nested_lst):
    if len(nested_lst) == 0:
        return "The initial list is empty!"
    try:
        return [item for lst in nested_lst for item in lst]
    except TypeError:
        return "The initial list is not nested!"

print(flatten_([[1,2],[3,4],[5]]), flatten_([3,2,1]), flatten_([]))          

[1, 2, 3, 4, 5] The initial list is not nested! The initial list is empty!


### 3. Custom Sorting

Given a list of tuples (name, age), sort by age descending, then name ascending.

In [32]:
import string

def sort_name_age(nested_lst, age=True):
    
    alphabet = string.ascii_uppercase
    dict_alpha = {alphabet[k]: k for k in range(len(alphabet))}

    swaped = False
    if age:
        for i in range(len(nested_lst) - 1):
            if nested_lst[i][1] < nested_lst[i+1][1]:
                nested_lst[i], nested_lst[i+1] = nested_lst[i+1], nested_lst[i]
                swaped = True         
        if swaped:
            sort_name_age(nested_lst)
                  
    swaped = False
    for j in range(len(nested_lst) - 1):
        letter1 = nested_lst[j][0][0].upper()
        letter2 = nested_lst[j+1][0][0].upper()
        if dict_alpha[letter1] > dict_alpha[letter2]:
            temp_item = nested_lst[j]
            nested_lst[j], nested_lst[j+1] = nested_lst[j+1], nested_lst[j]
            swaped = True      
    if swaped:
        sort_name_age(nested_lst, False)
           
    return nested_lst
        
print(sort_name_age([("Loghman", 34), ("ali", 87), ("omid", 41), ("zahra", 98)]))      

[('ali', 87), ('Loghman', 34), ('omid', 41), ('zahra', 98)]


### 4. Class: Vector2D

Write a Vector2D class with:

attributes x and y

methods:

magnitude()

add(other) → returns new Vector

`__repr__`

In [44]:
import math

class Vector2D:
    
    def __init__(self, x, y):
        self.vector2d = np.array([[x, y]])
        
    def magnitude(self):
        return np.sqrt(np.sum(self.vector2d**2))
        
    def add(self, other):
        return other + self.vector2d
        
    def __repr__(self):
        return f"Vector2D{self.vector2d}"

oth = np.array([[3, 6]])
obj = Vector2D(6, 9)
print(obj.magnitude())
print(obj.add(oth))
print(repr(obj))

10.816653826391969
[[ 9 15]]
Vector2D[[6 9]]


### 5. Implement a Simple Decorator

Write a decorator @timer that measures and prints function execution time.

In [52]:
import time

def timer(func):
    def wraper(*args, **kwargs):
        tic = time.time()
        result = func(*args, **kwargs)
        toc = time.time()
        print(f"Execution Time: {round(toc - tic, 5)} s")
        return result
    return wraper

@timer
def addition(x, y, z):
    count = 0
    for i in range(1000):
        count += x + y + z
    return count

addition(3, 4, 5)   

Execution Time: 0.00022 s


12000

### 6. Exception Handling

Write a function that:

divides two numbers

catches ZeroDivisionError

returns "undefined" on division by zero

In [56]:
def division(num1, num2):
    try:
        return num1 / num2
        
    except ZeroDivisionError:
        return "Undefined!"
        
print(division(12, 3), division(13, 3), division(4, 0))

4.0 4.333333333333333 Undefined!


### 7. Dictionary Comprehension

From a sentence, build a dictionary that maps each word to its frequency.
Use a dictionary comprehension.

In [61]:
def dict_creator(sent):
    sent_split = sent.split()
    sent_set = list(set(sent_split))
    return {word: sent_split.count(word) for word in sent_set}
    
print(dict_creator("i am not interested in this work but i am intersted in that work"))

{'am': 2, 'but': 1, 'in': 2, 'interested': 1, 'i': 2, 'that': 1, 'not': 1, 'this': 1, 'intersted': 1, 'work': 2}


### 8. NumPy Broadcasting

Using NumPy, create a 3×3 matrix and add a 1D vector of size 3 to each row.

Example:

    matrix + vector

In [66]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([5, 5, 5])
print(x + y)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### 9. Matrix Multiplication (NumPy and Manual)

Implement matrix multiplication:

once using numpy.dot()

once manually using loops

In [75]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2], [3, 4], [5, 6]])
print(np.dot(x, y))

z = []
for i in range(x.shape[0]):
    row = []
    for j in range(y.shape[1]):
        sum_ = 0
        for k in range(y.shape[0]):
            sum_ += x[i, k] * y[k, j]
        row.append(sum_)
    z.append(row)
    
print(np.array(z))        

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]


### 10. File Parsing & Aggregation

Assume a file records.csv has lines like:

Alice, 5
Bob, 3
Alice, 7

Write Python code to:

read the file

sum the values for each name

output a dictionary: {"Alice": 12, "Bob": 3}

In [79]:
def read_csv_(file_path):
    dict_ = {}
    with open(file_path, "r") as file:
        for line in file:
            name, num = line.strip().split(",")
            num = int(num)

            if name in dict_:
                dict_[name] += num
            else:
                dict_[name] = num
    return dict_
            
print(read_csv_("/home/loqman/Downloads/projs/deep-learning/technical_interview/csv_file.csv"))   

{'Loqman': 77, 'Ali': 45, 'Omid': 100043, 'Jaqub': 40}
